version: '3'

services:
    function:
        build: .
        volumes:
            - ".:/src"
        env_file:
            - .env
        cap_add:
            - SYS_PTRACE
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - SA_PASSWORD=${LOCAL_PASSWORD:-r00t.R00T}
            - ACCEPT_EULA=1

volumes:
    redis_data:
        driver: local
